version: '3.8'
services:
  sonarqube:
    image: sonarqube:9.5-community
    platform: linux/amd64
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - ./app/node_modules

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: